---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: loadgen
spec:
  parallelism: 1
  quiet: "false"
  cleanup: "post"
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "loadgen"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/hostname: worker-2
    volumeMounts:
      - name: test-data
        mountPath: /test-data
    volumes:
      - name: test-data
        configMap:
          name: loadgen-script
  initializer:
    volumeMounts:
      - name: test-data
        mountPath: /test-data
    volumes:
      - name: test-data
        configMap:
          name: loadgen-script
  script:
    configMap:
      name: 'loadgen-script'
      file: 'loadgen.js'
